---
repos:
  # === YAML ===
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
        files: \.(yml|yaml)$

  # === Markdown ===
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.20.0
    hooks:
      - id: markdownlint-cli2
        args: ["--config", ".markdownlint-cli2.yaml"]
        files: \.md$

